[package]
name = "tom_bot"
version = "0.1.0"
edition = "2021"
authors = ["***REMOVED***siah Bull <***REMOVED***siah.bull7@gmail.com>"]

[dependencies]
chrono = { git = "https://github.com/chronotope/chrono", rev="378efb157d674c01761f538d4450705c2b1766a4" }
log = "0.4.17"
fern = "0.6.1"

dotenv = "0.15.0"

tokio = { version = "1", features = ["full"] }
serenity = { git="https://github.com/serenity-rs/serenity", branch="next", default-features = false, features = ["full"] }

# distance command
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
fantoccini = "0.19.3"

# sea-orm = "0.9.2"
