[package]
name = "tom_bot"
version = "0.1.0"
edition = "2021"
authors = ["***REMOVED***siah Bull <***REMOVED***siah.bull7@gmail.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
serenity = { version = "0.11.5" }
dotenv = "0.15.0"

log = "0.4.17"
tracing = "0.1.36"

# sea-orm = "0.9.2"