[package]
name = "tom_bot"
version = "0.1.0"
edition = "2021"
authors = ["Josiah Bull <josiah.bull7@gmail.com>"]

[dependencies]
chrono = "0.4.22"
log = "0.4.17"
fern = "0.6.1"

dotenv = "0.15.0"

tokio = { version = "1", features = ["full"] }
serenity = { version = "0.11.5", default-features = false, features = ["tokio", "builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "collector"] }

# sea-orm = "0.9.2"
