version: "3.3"

networks:
  tombot_backend:
    name: tombot_backend
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

services:
  postgres:
    restart: unless-stopped
    image: postgres
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=tombot
      - POSTGRES_PASSWORD=tombot
      - POSTGRES_DB=tombot
    networks:
      tombot_backend:
        ipv4_address: 10.10.0.2
    ports:
      - 5432:5432

  tombot:
    build: .
    container_name: tombot
    depends_on:
      - postgres
    restart: always
    environment:
      - DISCORD_TOKEN
      - GOOGLE_MAPS_TOKEN
      - POSTGRES_USER
      - POSTGRES_PASS
      - TZ="Pacific/Auckland"
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tombot
      - RUST_BACKTRACE=full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/app/config.toml
    networks:
      tombot_backend:
        ipv4_address: 10.10.0.3

  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - tombot
