version: "3.3"

networks:
  tombot_backend:
    name: tombot_backend
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
services:
  postgres:
    restart: unless-stopped
    image: postgres
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_DB=tombot
    networks:
      tombot_backend:
        ipv4_address: 10.10.0.2
  geckodriver:
    image: ghcr.io/josiahbull/tombot-gecko-driver:main
    container_name: geckodriver
    restart: always
    ports:
      - 4444:4444
    environment:
      - TZ="Pacific/Auckland"
    networks:
      tombot_backend:
        ipv4_address: 10.10.0.4

  tombot:
    image: ghcr.io/josiahbull/tombot:main
    container_name: tombot
    depends_on:
      - geckodriver
      - postgres
    restart: always
    environment:
      - DISCORD_TOKEN
      - GOOGLE_MAPS_TOKEN
      - POSTGRES_USER
      - POSTGRES_PASS
      - TZ
      - GECKO_DRIVER=http://10.10.0.4:4444/
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tombot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/app/config.toml
    networks:
      tombot_backend:
        ipv4_address: 10.10.0.3

  autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - tombot
